name: Mypy

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    main:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"
            - name: Install Dependencies
              run: |
                  sudo apt-get update -qq
                  sudo apt-get install -y libcurl4-openssl-dev libpython3-dev libssl-dev
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install apprise==1.9.4 minio==7.2.18
                  pip install mypy==1.18.2 django-stubs==5.2.7 types-pycurl==7.45.2.20240311 types-Markdown types-pygments
                  touch hc/local_settings.py
            - name: Run Mypy
              run: mypy --strict --show-traceback hc
